# Generated by Django 6.1.1 on 2026-10-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='user@cloud.com', max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
