# Generated by Django 6.1.1 on 2026-10-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudtable',
            old_name='mobile',
            new_name='mob',
        ),
        migrations.AddField(
            model_name='cloudtable',
            name='profile_pic',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
